import = ["~/.config/alacritty/color-catpuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 17.0

[font.normal]
family = "M+1Code Nerd Font Mono"
style = "Regular"
