- hosts: all
  become: true

  tasks:
    - name: Allow apt to use a repository over HTTPS
      apt:
        update_cache: yes
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable"
        state: present
    - name: Install Docker engine
      apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Create docker group
      group:
        name: docker
        state: present
    - name: Add user to docker group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: docker
        append: yes
    # - name: Activate the changes to groups
    #   command: newgrp
